# Generated by Django 4.1.6 on 2023-02-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=35)),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128, null=True, verbose_name='password')),
                ('email', models.EmailField(default='example@example.com', max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
