# Generated by Django 3.0.7 on 2023-02-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('cedula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=35)),
                ('role', models.CharField(max_length=35)),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('age', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=10)),
                ('code_qr', models.CharField(max_length=35)),
            ],
        ),
    ]
