# Generated by Django 4.1.6 on 2023-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
