# Generated by Django 4.1.6 on 2023-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
